### ISSUE TITLE
p.163のchapter5.ipynbの誤植について

### ISSUE THREAD

**Issue by shimor69** [mohzeki222/ohm_princess#2]
第1版p.163の「(魔法の言葉：関数で適当なデータを作る)」の箇所について
`tdata = (np.sin(xdata) + 2.0*np.sin(2.0*xdata))..astype(np.float32)`
となっていますが、
`tdata = (np.sin(xdata) + 2.0*np.sin(2.0*xdata)).astype(np.float32)`
の間違いかと思うのですがどうでしょうか。

**Comment by Makimakima72** [comment]
間違い箇所ですが、以下箇所かと思います。
誤り
tdata = (np.sin(ndata) + np.sin(2.0*ndata)).reshape(D,N)..astype(np.float32)
正解
tdata = (np.sin(xdata) + 2.0*np.sin(2.0*xdata)).astype(np.float32)

**Comment by shimor69** [comment]
なるほど！今度やってみます。ありがとうございます。
